### ISSUE TITLE
ÉcoSynope Dynamic Rate

### ISSUE THREAD

**Issue by Hubitat4me** [claudegel/Hubitat-sinope-GT125#4]
Hi Claude, Is it possible to recover the event when my thermostats are placed in Dynamic Rate (DR) mode? I would like to be able to use this state change to trigger an action.
Thx

**Comment by rfg81** [comment]
I don't have access to this event. There are some discussions about this here https://community.hubitat.com/t/handling-electricity-dynamic-pricing-flex-d/108211/20
